steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--vpc-egress'
      - 'all-traffic'
      - '--set-env-vars'
      - 'NODE_ENV=production,GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},NEXTAUTH_URL=${_NEXTAUTH_URL},AUTH_URL=${_NEXTAUTH_URL},DB_PORT=${_DB_PORT},MYTHORIA_DB=${_MYTHORIA_DB},WORKFLOWS_DB=${_WORKFLOWS_DB_NAME},BACKOFFICE_DB=${_BACKOFFICE_DB_NAME},GOOGLE_CLOUD_PROJECT_ID=${_GOOGLE_CLOUD_PROJECT_ID},WEBAPP_URL=${_WEBAPP_URL},ADMIN_URL=${_ADMIN_URL},STORY_GENERATION_WORKFLOW_URL=${_STORY_GENERATION_WORKFLOW_URL},NOTIFICATION_ENGINE_URL=${_NOTIFICATION_ENGINE_URL},DB_MAX_CONNECTIONS=${_DB_MAX_CONNECTIONS}'
      - '--set-secrets'
      - 'AUTH_SECRET=mythoria-auth-secret:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,DB_HOST=mythoria-db-host:latest,DB_USER=mythoria-db-user:latest,DB_PASSWORD=mythoria-db-password:latest,ADMIN_API_KEY=ADMIN_API_KEY:latest,NOTIFICATION_ENGINE_API_KEY=NOTIFICATION_ENGINE_API_KEY:latest'

# Default substitutions
substitutions:
  _SERVICE_NAME: 'mythoria-admin'
  _REGION: 'europe-west9'
  # Non-sensitive configuration variables
  _GOOGLE_CLIENT_ID: '803421888801-fsse90vkqpobthd3runvv60dfijnh63t.apps.googleusercontent.com'
  _NEXTAUTH_URL: 'https://mythoria-admin-803421888801.europe-west9.run.app'
  _DB_PORT: '5432'
  _MYTHORIA_DB: 'mythoria_db'
  _WORKFLOWS_DB_NAME: 'workflows_db'
  _BACKOFFICE_DB_NAME: 'backoffice_db'
  _GOOGLE_CLOUD_PROJECT_ID: 'oceanic-beach-460916-n5'
  _WEBAPP_URL: 'https://mythoria.pt'
  _ADMIN_URL: 'https://mythoria-admin-803421888801.europe-west9.run.app'
  _STORY_GENERATION_WORKFLOW_URL: 'https://story-generation-workflow-803421888801.europe-west9.run.app'
  _NOTIFICATION_ENGINE_URL: 'https://notification-engine-803421888801.europe-west9.run.app'
  _DB_MAX_CONNECTIONS: '10'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

timeout: '1200s'
